name: Process Docker

on:
  push:
    branches:
    # Sequence of patterns matched against refs/tags
    tags:

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        with:
          registry: hfjcmwgl.gra5.container-registry.ovh.net
          username: ${{ secrets.CS_HARBOR_USERNAME }}
          password: ${{ secrets.CS_HARBOR_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/ewocs1processing
          # Do not generate :latest tag on Git push tag
          # See https://github.com/marketplace/actions/docker-metadata-action#latest-tag
          flavor: |
            latest=false
          # generate Docker tags based on the following events/attributes
          # See https://github.com/marketplace/actions/docker-metadata-action#tags-input
          tags: |
            type=ref,event=branch
            type=ref,suffix=-{{sha}},event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            EWoC
      # Extract COTS versions from Dockerfile
      - name: COTS Versions
        id: cots-versions
        run: |
          sed -n '/^ARG/s/ARG *\(.*\)=\(.*\)/::set-output name=\1::\2/p' Dockerfile
      - name: Download Dataship
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_dataship"
          tag: "${{ steps.cots-versions.outputs.EWOC_DATASHIP_VERSION }}"
          fileName: "dataship-${{ steps.cots-versions.outputs.EWOC_DATASHIP_VERSION }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Download S1Tiling
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_s1tiling"
          tag: "${{ steps.cots-versions.outputs.S1TILING_VERSION }}"
          fileName: "S1Tiling-${{ steps.cots-versions.outputs.S1TILING_VERSION }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Download EWoC S1
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_s1"
          tag: "${{ steps.cots-versions.outputs.EWOC_S1_VERSION }}"
          fileName: "ewoc_s1-${{ steps.cots-versions.outputs.EWOC_S1_VERSION }}.tar.gz"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Download EOTile
        uses: robinraju/release-downloader@v1.1
        with:
          repository: "WorldCereal/ewoc_eotile"
          tag: "${{ steps.cots-versions.outputs.EOTILE_VERSION }}"
          fileName: "eotile-${{ steps.cots-versions.outputs.EOTILE_VERSION }}-py3-none-any.whl"
          token: ${{ secrets.CS_ORG_TOKEN }}
      - name: Build Docker images
        id: docker-build
        uses: docker/build-push-action@v2.5.0
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=NAME::${GITHUB_REF#refs/heads/}
      - name: Validate
        uses: addnab/docker-run-action@v3
        with:
          image: hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/ewocs1processing:${{ steps.branch-name.outputs.NAME }}@${{ steps.docker-build.outputs.digest }}
          run: /opt/entrypoint.sh python --version
